version: "3.9"
services:
    db:
        image: postgres:14.1
        container_name: postgres_db
        environment:
          - POSTGRES_NAME=docker_lab
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=tech
        volumes:
          - postgres_data:/var/lib/postgresql/data
    web:
        build: .
        image: acstestck.azurecr.io/django-web:latest
        container_name: django_web
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
          - .:/app
        ports:
          - "8000:8000"
        environment:
          - POSTGRES_NAME=docker_lab
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=tech
        depends_on:
          - db
volumes:
  postgres_data:

