version: "3.9"

services:
  db:
    image: postgres:14.1
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: docker_lab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tech
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    image: acstestck.azurecr.io/django-web:latest
    container_name: django_web
    restart: always
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: docker_lab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tech
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db

volumes:
  postgres_data:

