name: Django ACR Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1Ô∏è‚É£ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2Ô∏è‚É£ Login to Azure Container Registry
      - name: Login to ACR
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login \
            ${{ secrets.ACR_LOGIN_SERVER }} \
            -u ${{ secrets.ACR_USERNAME }} \
            --password-stdin

      # 3Ô∏è‚É£ Build Docker image
      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.ACR_LOGIN_SERVER }}/django-web:latest .

      # 4Ô∏è‚É£ Push image to ACR
      - name: Push image to ACR
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/django-web:latest

      # 5Ô∏è‚É£ Deploy on Server via SSH
      - name: Deploy on VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            echo "üîê Login to ACR on server"
            echo "${{ secrets.ACR_PASSWORD }}" | docker login \
              ${{ secrets.ACR_LOGIN_SERVER }} \
              -u ${{ secrets.ACR_USERNAME }} \
              --password-stdin

            echo "üìÇ Moving to project directory"
            cd /home/stage/django

            echo "‚¨áÔ∏è Pulling latest image"
            docker-compose pull web

            echo "üõë Stopping containers"
            docker-compose down

            echo "üöÄ Starting updated containers"
            docker-compose up -d

            echo "üì¶ Running migrations"
            #docker-compose exec -T web python manage.py migrate
            #./import.sh

            #echo "üé® Collecting static files"
            #docker-compose exec -T web python manage.py collectstatic --noinput

            echo "‚úÖ ACR Deployment completed successfully"

